#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          motorSensor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorHang,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorRoller,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int deadzone = 15;

void hangTask() { 					// Assign a task for the hanging method
	if(joy1Btn(2) == 1){			// If the button is pressed
		motor[motorHang] = 70;		// The motor is put to 70% power
	}else{
		motor[motorHang] = 0;		// If it's not pressed power goes to 0%
	}
}

void flagTask() { 					// Assign a task for the flag method
if(joy1Btn(1) == 1){				// If the button is pressed
	motor[motorFlag] = 70; 			// The motor is put to 70% power
	}else{
		motor[motorFlag] = 0;		// If it's not pressed power goes to 0%


	}
}


}
// Allows left joystick to activate the lift.
void liftTask() {
if(abs(joystick.joy2_y1) > deadzone) {
	motor[motorLift] = joystick.joy2_y2;
}	else{
	motor[motorLift] = 0;
}
}


// Allows right joystick to activate the roller.
void rollerTask() {
if(abs(joystick.joy2_y2) > deadzone){
	motor[motorRoller] = joystick.joy2_y2;
}else{
	motor[motorRoller] = 0;
}
}
// Allows right joystick to allow the chassis to drive.
void driveTask(){
	// Tank drive with deadzone
	if(abs(joystick.joy1_y2) > deadzone){
			motor[motorRight] = joystick.joy1_y2;
	}else{
	motor[motorRight] = 0;
	}

	if(abs(joystick.joy1_y1) > deadzone){
		motor[motorLeft] = joystick.joy1_y1;
	}else{
	motor[motorLeft] = 0;
	}
}


void initializeRobot()
{


  return;
}




task main()
{


  initializeRobot();

  waitForStart();

  while (true)
  {
  getJoystickSettings(joystick);
	driveTask();
	rollerTask();
	liftTask();
  }
}
