#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//test code for manipulation of motorspeed through buttons
/*
	Zenith 2939
	Ken
*/

#include "JoystickDriver.c"

void initializeRobot()
{
  return;
}


task main()
{
  initializeRobot();

  waitForStart();

  while (true)
  {
		getJoystickSettings(joystick);


  }
}
